package kr.caredoc.careinsurance.user

interface ExternalCaregivingManagerCreationCommandHandler {
    fun createExternalCaregivingManager(command: ExternalCaregivingManagerCreationCommand): ExternalCaregivingManagerCreationCommandResult
}
