package kr.caredoc.careinsurance.reception.modification

interface CaregivingRoundModificationSummaryByReceptionIdQueryHandler {
    fun getCaregivingRoundModificationSummary(query: CaregivingRoundModificationSummaryByReceptionIdQuery): CaregivingRoundModificationSummary
}
