package kr.caredoc.careinsurance.reception.modification

interface CaregivingChargeModificationSummaryByReceptionIdQueryHandler {
    fun getCaregivingChargeModificationSummary(query: CaregivingChargeModificationSummaryByReceptionIdQuery): CaregivingChargeModificationSummary
}
