package kr.caredoc.careinsurance.caregiving

enum class ClosingReasonType {
    FINISHED,
    FINISHED_USING_PERSONAL_CAREGIVER,
    FINISHED_CONTINUE,
    FINISHED_RESTARTING,
    FINISHED_CHANGING_CAREGIVER,
    FINISHED_CHANGING_HOSPITAL,
    FINISHED_CHANGING_CAREGIVER_AND_HOSPITAL,
    CANCELED_WHILE_REMATCHING,
    CANCELED_USING_PERSONAL_CAREGIVER,
}
