package kr.caredoc.careinsurance.settlement.statistics

interface DailySettlementTransactionStatisticsByDateQueryHandler {
    fun getDailySettlementTransactionStatistics(query: DailySettlementTransactionStatisticsByDateQuery): DailySettlementTransactionStatistics?
}
