package kr.caredoc.careinsurance.agency

interface ExternalCaregivingOrganizationCreationCommandHandler {
    fun createExternalCaregivingOrganization(command: ExternalCaregivingOrganizationCreationCommand): ExternalCaregivingOrganizationCreationResult
}
